import React from 'react';
const profileImage = require('./../images/logo.png')

const AboutPage = (props)=>{
	return(
	<div className="about-page">
        <img src={profileImage} alt="profileImage"></img>
		<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacus odio, ultricies laoreet orci dignissim, dignissim fermentum nisl. Vivamus tincidunt nisi mi, eu aliquet ligula cursus ut. Ut pretium mi at tortor fermentum vulputate. Quisque eu venenatis justo, vel facilisis lectus. Sed consequat rhoncus libero, eu cursus nisl consectetur ut. Nullam fringilla consectetur lacus, in volutpat enim elementum sit amet. Nulla gravida eros ut ante euismod, id iaculis erat feugiat. Cras sem ante, luctus quis lacus eget, aliquet imperdiet augue. Quisque interdum consectetur nisi et scelerisque. Vivamus faucibus consequat erat eu efficitur. Nullam faucibus pharetra hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sit amet mollis nulla. Donec ultricies purus at tellus mollis tempus. Aliquam at pretium lorem. Vivamus pharetra tellus lacus, posuere maximus mauris fermentum quis. Ut in orci quis dui tempus scelerisque. In hendrerit metus vitae fermentum varius. Cras quis enim neque. Proin ipsum augue, gravida ac dictum id, bibendum nec sem. Maecenas ac bibendum purus. Aenean purus diam, cursus eu nibh bibendum, venenatis egestas felis. Nunc interdum purus sem, vitae viverra ipsum sollicitudin at. Curabitur in ligula nec mi sagittis suscipit. Nulla consectetur imperdiet venenatis. Aliquam fermentum tristique nisi et blandit. Mauris gravida sapien vitae dui scelerisque consectetur. Nullam eu suscipit eros. Quisque ultrices sem sed ultrices tincidunt. Duis iaculis purus non mi consequat, vel vestibulum odio ultrices. Aenean non laoreet ex. Duis nisl mauris, malesuada tincidunt vestibulum sed, ornare nec erat. Fusce at sem efficitur, mollis risus vel, laoreet nunc. Cras sed cursus urna. Maecenas in aliquam urna. Nulla eget lobortis tortor. Donec vestibulum purus non elit cursus, a congue magna pellentesque. In nec tortor nec neque lobortis ultrices in sit amet risus. Quisque vitae tempus enim. Donec sed eros leo. Sed dictum diam tortor, quis commodo risus pretium a. Fusce vitae elit et ex efficitur gravida id eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc pellentesque vulputate tristique. Donec molestie eros at augue semper, interdum congue arcu elementum. Cras mi elit, maximus at congue at, venenatis vitae neque. Maecenas est ligula, venenatis in ex non, hendrerit sagittis velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sollicitudin interdum euismod. Duis elit quam, interdum a leo eu, pulvinar cursus justo.</div>
	</div>
	);
}

export default AboutPage